### ISSUE TITLE
Bug: 每日自动作战中心相本日常出现不执行的错误

### ISSUE THREAD

**Issue by Bl1tzcrank** [MaaAssistantArknights/M9A#35]
bug信息大概在log的13479-14175行
一直重复检索模拟器截图和resource中匹配的图片
但其它的执行包括活动的刷取和每日报酬都是正常的
[maa.log](https://github.com/MaaAssistantArknights/MAA1999/files/12906184/maa.log)

**Comment by dongwlin** [comment]
心相只打每天免费的

**Comment by Bl1tzcrank** [comment]
> 心相只打每天免费的

就是每天送的那两次 进去之后不调整复现次数直接就开始刷了 我看了config里面也不能改心相的复现次数 会不会是我模拟器的问题 对点击不响应什么的

**Comment by Trust04zh** [comment]
只执行一次的问题大概是pipeline里切复现的逻辑有点缺陷，预期#45会优化

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaFramework/commit/928c84961e3f4f4bbcff5f4f144b77ca6f2cdc93 fixed

如果 v0.6.1 之后的版本再遇到可以再发下日志看看
