### ISSUE TITLE
不自动领取奖励

### ISSUE THREAD

**Issue by CCCClaus** [MaaAssistantArknights/M9A#41]
config里已经有让他自动领取奖励Awards，但是它不领取

日志：
[maa.log](https://github.com/MaaAssistantArknights/MAA1999/files/13068594/maa.log)
实际截图：
![image](https://github.com/MaaAssistantArknights/MAA1999/assets/116964544/0767aa8a-b04a-4586-a715-d9366040020f)
版本：
v0.5.3

**Comment by MistEO** [comment]
新版本是不是没这个问题了？

**Comment by CCCClaus** [comment]
> 新版本是不是没这个问题了？

嗯嗯是的，谢谢大佬，忘关issue了
