### ISSUE TITLE
运行时跳红字了，问下这是什么原因

### ISSUE THREAD

**Issue by cyt0417** [MaaAssistantArknights/M9A#52]
![7U`S6~~ Q E{7 T8PF91AB8(1)](https://github.com/MaaAssistantArknights/M9A/assets/150600107/1e203fe6-2759-463f-8446-20ab30a1fe0c)

**Comment by MistEO** [comment]
截图出错，模拟器的问题，会自动重试的，不影响。如果频繁跳可以考虑换模拟器
