### ISSUE TITLE
M9A_CLI.exe 执行任务报错：Failed to init Maa instance, a connection error or resource file corruption occurred

### ISSUE THREAD

**Issue by KaronGH** [MaaAssistantArknights/M9A#62]
版本：最新版
模拟器：MuMu，连接应该没问题（刚连过MAA，adb.exe已经kill）
终端报错信息和maa.log如下
[maa.log](https://github.com/MaaAssistantArknights/M9A/files/14190653/maa.log)
[Terminal 报错信息.txt](https://github.com/MaaAssistantArknights/M9A/files/14190656/Terminal.txt)

**Comment by MistEO** [comment]
用 mumu 自带的 adb 试试（而不是你自己装的），另外用的是 mumu6 吗？怎么是 7555 的端口

**Comment by KaronGH** [comment]
自带的可行，因为我这个是古早MuMu版本（Version 2.5.23.4），所以是7555端口
