### ISSUE TITLE
蓝叠模拟器执行任务闪退

### ISSUE THREAD

**Issue by Ryan-4327** [MaaAssistantArknights/M9A#65]
ADB自动读取，手动输入MAA的数据也会闪退
蓝叠国际版

![image](https://github.com/MaaAssistantArknights/M9A/assets/115599668/5f092ddf-31d3-4ae0-80d2-04e2d3f4cf96)

![image](https://github.com/MaaAssistantArknights/M9A/assets/115599668/18048696-5d2f-4a6b-a492-0b92d1d9152c)

![image](https://github.com/MaaAssistantArknights/M9A/assets/115599668/12687d0b-184d-4ac7-a4fa-4a352515d573)

[maa.log](https://github.com/MaaAssistantArknights/M9A/files/14280056/maa.log)

### Current configuration ###

Controller:
        ADB
                C:/Program Files/BlueStacks_nxt/HD-Adb.exe
                emulator-5554

**Comment by MistEO** [comment]
修了下，试试 beta.2 版本

**Comment by Ryan-4327** [comment]
已能正常使用，非常感谢！！！

（Controller）Adb - Auto detect - 出现的1和2都可以正常使用了
