### ISSUE TITLE
新PiCli无法正常运行

### ISSUE THREAD

**Issue by CCCClaus** [MaaAssistantArknights/M9A#66]
配置完新的config后，选择运行但是命令行界面无响应

[截图.zip](https://github.com/MaaAssistantArknights/M9A/files/14307753/default.zip)
（不知道为啥图片截图拖不上来）

对应的模拟器内也没有操作

（adb路径错误时会正常报错，所以我觉得现在adb路径没错）

下附config和log
[maa_pi_config.json](https://github.com/MaaAssistantArknights/M9A/files/14307729/maa_pi_config.json)
[maa_toolkit.json](https://github.com/MaaAssistantArknights/M9A/files/14307731/maa_toolkit.json)
[maa.log](https://github.com/MaaAssistantArknights/M9A/files/14307733/maa.log)

**Comment by MistEO** [comment]
临时解决方法：更新到 beat.3，把 interface.json 里 screencap 改成 196608

**Comment by CCCClaus** [comment]
> 临时解决方法：更新到 beta.3，把 interface.json 里 screencap 改成 196608
> 
> ![image](https://private-user-images.githubusercontent.com/18511905/305382215-dc35d218-3618-4fdc-b165-8abff06b18cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODQ3NzgsIm5iZiI6MTcwODA4NDQ3OCwicGF0aCI6Ii8xODUxMTkwNS8zMDUzODIyMTUtZGMzNWQyMTgtMzYxOC00ZmRjLWIxNjUtOGFiZmYwNmIxOGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDExNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMjlkZDY4MjZmOGJjNzUzYzVjN2IwODY2ODk5M2M5NzljMWI1YmRlYzY4Yjk3YjhjMjk2NjlmMjJlYjk5MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XFIj2CQc7RxZ6rGZXO8OIJZ_DiwlEOYaZlINJ3mF5Xg)

感谢玛丽，这样可以正常运行了。
